version: '3'

services:
  nfs-server:
    build:
      context: .
      dockerfile: Dockerfile-server
    volumes:
      - nfs_data:/data/nfs
    ports:
      - "111:111/udp"
      - "2049:2049/tcp"
    restart: always

  nfs-client:
    build:
      context: .
      dockerfile: Dockerfile-client
    volumes:
      - nfs_data:/data/nfs
    depends_on:
      - nfs-server
    restart: always

volumes:
  nfs_data:
    driver: local